version: '3'
services:
  config-server:
    container_name: config-server
    build:
      context: centralize_config_server
      dockerfile: Dockerfile
    image: "lampt1210/first-repo:cmcdemo-config-server"
    ports:
      - "9999:9999"
    networks:
      ms-network:
        ipv4_address: 172.19.0.6

  discovery-service:
    depends_on:
      - config-server
    container_name: discovery-service
    build:
      context: discovery_server
      dockerfile: Dockerfile
    image: "lampt1210/first-repo:cmcdemo-discovery-service"
    ports:
      - "8888:8888"
    networks:
      ms-network:
        ipv4_address: 172.19.0.3
  
  gateway-service:
    depends_on:
      - config-server
      - discovery-service
    container_name: gateway-service
    build:
      context: gateway-cmc-demo
      dockerfile: Dockerfile
    image: "lampt1210/first-repo:cmcdemo-gateway-service"
    ports:
      - "8083:8083"
    networks:
      ms-network:
        ipv4_address: 172.19.0.4

  user-service:
    depends_on:
      - gateway-service
    container_name: user-service
    build:
      context: user_management
      dockerfile: Dockerfile
    image: "lampt1210/first-repo:cmcdemo-user-service"
    ports:
      - "8082:8082"
    networks:
      ms-network:
        ipv4_address: 172.19.0.5

networks:
  ms-network:
    external:
      name: ms-network